### ISSUE TITLE
WSL2 Docker with Testcontainers

### ISSUE THREAD

**Issue by maranmaran** [HofmeisterAn/dotnet-testcontainers#459]
Greetings, please label this as question :) 

I have recently switched from having Docker Desktop to diy WSL2 docker.
I've installed Ubuntu-20.04 distro and on it docker.

I've added this WSL2 distro IP as DOCKER_HOST env like `tcp://{ip}`
I've downloaded docker.exe and put it in C:/bin and mapped that in Path variables.

With that set now I can execute commands from my cmd / ps -> `docker run --rm hello-world`
Without the need to specify `-H tcp://ip `

With that in place I modified my testcontainers tests to use `.WithDockerEndpoint(...DOCKER_HOST...)`

I get this as output when starting the container:
`
System.TimeoutException
The operation has timed out.
   at System.IO.Pipes.NamedPipeClientStream.ConnectInternal(Int32 timeout, CancellationToken cancellationToken, Int32 startTime)
`

Which stems from `Docker.DotNet.DockerClient.PrivateMakeRequestAsync`

Do you perhaps know what I'm missing or what should I configure extra to allow testcontainers to work?

Is it perhaps some entrypoint like where my docker.exe is located or similar?

**Comment by HofmeisterAn** [comment]
I can't say much without the full stack trace, but I guess you need to disable the resource reaper before starting any container (`TestcontainersSettings.ResourceReaperEnabled = false`).

**Comment by maranmaran** [comment]
@HofmeisterAn I've updated to prerelease and added the flag.

Here's full stacktrace:

```
System.TimeoutException
The operation has timed out.
   at System.IO.Pipes.NamedPipeClientStream.ConnectInternal(Int32 timeout, CancellationToken cancellationToken, Int32 startTime)
   at System.IO.Pipes.NamedPipeClientStream.<>c__DisplayClass20_0.<ConnectAsync>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Docker.DotNet.DockerClient.<>c__DisplayClass6_0.<<-ctor>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Net.Http.Client.ManagedHandler.ProcessRequestAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Net.Http.Client.ManagedHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Docker.DotNet.DockerClient.PrivateMakeRequestAsync(TimeSpan timeout, HttpCompletionOption completionOption, HttpMethod method, String path, IQueryString queryString, IDictionary`2 headers, IRequestContent data, CancellationToken cancellationToken)
   at Docker.DotNet.DockerClient.MakeRequestAsync(IEnumerable`1 errorHandlers, HttpMethod method, String path, IQueryString queryString, IRequestContent body, IDictionary`2 headers, TimeSpan timeout, CancellationToken token)
   at Docker.DotNet.SystemOperations.GetSystemInfoAsync(CancellationToken cancellationToken)
   at DotNet.Testcontainers.Clients.DockerSystemOperations.GetIsWindowsEngineEnabled(CancellationToken ct)
   at DotNet.Testcontainers.Clients.TestcontainersClient.RunAsync(ITestcontainersConfiguration configuration, CancellationToken ct)
   at DotNet.Testcontainers.Containers.TestcontainersContainer.Create(CancellationToken ct)
   at DotNet.Testcontainers.Containers.TestcontainersContainer.StartAsync(CancellationToken ct)
   at IntegrationTests.Fixtures.IntegrationFixture.InitializeHost() in C:\backend\IntegrationTests\Fixtures\IntegrationFixture.cs:line 71
   at IntegrationTests.Fixtures.IntegrationFixture.InitializeAsync() in C:\backend\IntegrationTests\Fixtures\IntegrationFixture.cs:line 42
   at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code) in C:\Dev\xunit\xunit\src\xunit.core\Sdk\ExceptionAggregator.cs:line 90
```

My `docker.exe` is located in `C:\bin`
I have WSL2 configured and there i've started dockerd with -H and is listening on: `tcp://{ip_of_my_vm}:2735`
Windows environment variable has `DOCKER_HOST=tcp://{ip_of_my_vm}`
From windows using command prompt or powershell I'm able to run docker commands.

My testcontainers have added configuration `WithDockerEndpoint( tcp://{ip_of_my_vm} )` 

I get the above stacktrace

**Comment by HofmeisterAn** [comment]
> Windows environment variable has `DOCKER_HOST=tcp://{ip_of_my_vm}`

Does your env variable contain the port too? Do you set the variable either for the user or machine? It should be something like `DOCKER_HOST=tcp://localhost:2375`. Then set the Docker endpoint like this: `WithDockerEndpoint(Environment.GetEnvironmentVariable("DOCKER_HOST"))`. This runs fine on GitLab.

**Comment by HofmeisterAn** [comment]
@maranmaran does it work now?

**Comment by maranmaran** [comment]
> @maranmaran does it work now?

Sorry, haven't been active. 

As far as I remember i've managed to weed out new exception about TCP port not being available thus leading me to believe I must expose docker endpoint in my linux vm to my host machine in some way (I've looked into ufw and such). 

I can ping it (the endpoint) but my Test-NetConnection fails TCP 

No results yet and this issue is not tied to library definitely, but I'd keep it open if anyone wants to chip in on it or until I find how to make it work with this DIY docker

Hope that's fine, if not close it down.

**Comment by maranmaran** [comment]
Managed to get it working.

My UFW on Ubuntu 20.04 was disabled.
I picked up my VM host via  `hostname -I` or `ifconfig`

Started deamon with that host `dockerd -H ----`

Put that host as DOCKER_HOST on my machine and build the container (tcp://vm_host:2735)

Make sure you can access the api from browser on your host machine like so http://VM_HOST:2735/v1.40/images/json

This issue was related entirely to my local setup. I do not advise this for production use but rather local use.
